# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
printWidth: 120
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: false
jsxBracketSameLine: false
arrowParens: avoid
proseWrap: always
quoteProps: as-needed
tabWidth: 2
useTabs: false
