apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ['v1', 'v1beta1']
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: '/validate'
      caBundle: ''
    rules:
      - operations: ['CREATE']
        apiGroups: ['']
        apiVersions: ['v1']
        resources: ['pods']
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
kind: FlowSchema
metadata:
  name: health-for-strangers
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  rules:
    - nonResourceRules:
        - nonResourceURLs:
            - '/healthz'
            - '/livez'
            - '/readyz'
          verbs:
            - '*'
      subjects:
        - kind: Group
          group:
            name: 'system:unauthenticated'
---
apiVersion: example.io/v1
kind: SomeCustomResource
metadata:
  name: crd-example
spec:
  hello: world
