apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml

patchesJson6902:
  - path: overlays/production/argocd-server-deploy-command.yaml
    target:
      group: apps
      kind: Deployment
      name: argocd-server
      version: v1
