apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ['v1', 'v1beta1']
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: '/validate'
      caBundle: ''
    rules:
      - operations: ['CREATE']
        apiGroups: ['']
        apiVersions: ['v1']
        resources: ['pods']
---
apiVersion: example.io/v1
kind: SomeCustomResource
metadata:
  name: health-for-strangers
spec:
  hello: world
---
apiVersion: 'test-remove'
kind: Pod
metadata:
  name: pod-warning
  labels:
    app: pod-warning
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: false
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo I am running as user $(id -u)']
