apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
    app.kubernetes.io/name: rs
    app.kubernetes.io/instance: rs-1
    app.kubernetes.io/version: ""
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
